name: Docker CI

on:
  push:
  pull_request:

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  try_docker:
    uses: ./.github/workflows/docker-reusable.yml
    continue-on-error: true
    with:
      runs_on: "ubuntu-latest"

  fallback_docker:
    needs: [try_docker]
    if: needs.try_docker.result == 'failure'
    uses: ./.github/workflows/docker-reusable.yml
    with:
      runs_on: '[ "self-hosted", "linux" ]'
